### ISSUE TITLE
Missing user form

### ISSUE THREAD

**Issue by Paulius11** [Paulius11/Manager#45]
Paskutiniam pull requeste #42 @iamEJ  gali būt, kad per daug ištryniau kodo.

Patikrinau ankstesni commitą, rodė informaciją apie userį:

![Screenshot from 2020-08-16 16-04-03](https://user-images.githubusercontent.com/19476505/90335062-a27a2580-dfda-11ea-9c26-0cf7c51f8304.png)

O dabar rodo tik formą:

![Screenshot from 2020-08-16 16-08-13](https://user-images.githubusercontent.com/19476505/90335074-b9207c80-dfda-11ea-98eb-9c83bb28e7e7.png)

**Comment by iamEJ** [comment]
Čia skirtingi puslapiai turėtų būti. Parsisiųsiu ir pažiūrėsiu, kas negerai. Update puslapį turėtų taip pat matytis informacija.

**Comment by iamEJ** [comment]
UpdateUser ir UserProfile vienodas kodas. Gal todėl.

**Comment by Paulius11** [comment]
Veikia
